services:
  nakama:
    container_name: nakama
    image: registry.heroiclabs.com/heroiclabs/nakama:3.22.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up
        --database.address postgres:localdb@postgres:5432/nakama &&
        exec /nakama/nakama
        --name nakama1
        --database.address postgres:localdb@postgres:5432/nakama
        --logger.level DEBUG
        --session.token_expiry_sec 7200
    restart: always
    volumes:
      - ./nakama/data/:/nakama/data
    ports:
      - "7349:7349"   # console/grpc admin
      - "7350:7350"   # grpc/http
      - "7351:7351"   # websocket
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
      - share-network

networks:
  default:
    driver: bridge
  share-network:
    external: true
